/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 kotlin.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/kotlin-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve011.geometry} material={materials['SVGMat.013']} position={[-4.74, -1.28, 0.8]} rotation={[1.57, 0.02, -0.01]} scale={742.92}>
        <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.002']} />
        <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.003']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/kotlin-transformed.glb')
