/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 photo-frame.gltf --transform
Author: Xander Morningstar (https://sketchfab.com/XMorningstar)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/picture-frame-0ad9f5f4d1644317814a1c7934ff9624
Title: Picture Frame
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three";

export default function Model(props) {
  const { nodes, materials } = useGLTF("./models/photo-frame-transformed.glb");
  const texture = useLoader(TextureLoader, "./img/my-profile.jpeg");

  

  return (
    <group {...props}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.initialShadingGroup}
        rotation={[-Math.PI / 2, 0, 4.2]}
      >
        <meshStandardMaterial attach="material" color="#0c0c0c" />
      </mesh>
      <mesh position={[-0.1, 2.4, 0.05]} rotation={[5.9,-0.5,-0.18]}>
        <planeBufferGeometry args={[4.2, 4.2]} />
        <meshBasicMaterial map={texture}/>
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/photo-frame-transformed.glb");
