/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 spring-boot.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('./models/spring-boot-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve.geometry} material={materials['SVGMat.001']} position={[-6.18, 0, 0]} rotation={[-1.58, 0, -3.14]} scale={-982.47}>
        <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} />
      </mesh>
    </group>
  )
}

useGLTF.preload('./models/spring-boot-transformed.glb')
